name 'trlinkin-nsswitch'
version '0.0.1'
author 'Thomas Linkin'
source 'https://github.com/trlinkin/puppet-nsswitch'
summary 'Nsswtich Module'
description 'Module for managing the nsswitch.'
project_page'https://github.com/trlinkin/puppet-nsswitch'
